package topic

const (
	NEW_CHECK_PAD_ITEM     string = "NEW_CHECK_PAD_ITEM"
	CANCEL_CHECK_PAD_ITEM  string = "CANCEL_CHECK_PAD_ITEM"
	PREPARE_CHECK_PAD_ITEM string = "PREPARE_CHECK_PAD_ITEM"
	FORWARD_CHECK_PAD_ITEM string = "FORWARD_CHECK_PAD_ITEM"
	DELIVER_CHECK_PAD_ITEM string = "DELIVER_CHECK_PAD_ITEM"

	NEW_CHECK_PAD          string = "NEW_CHECK_PAD"
	OPEN_CHECK_PAD         string = "OPEN_CHECK_PAD"
	WAIT_PAYMENT_CHECK_PAD string = "WAIT_PAYMENT_CHECK_PAD"
	CANCEL_CHECK_PAD       string = "CANCEL_CHECK_PAD"
	PAY_CHECK_PAD          string = "PAY_CHECK_PAD"

	NEW_CUSTOMER  string = "NEW_CUSTOMER"
	NEW_PLACE     string = "NEW_PLACE"
	NEW_ATTENDANT string = "NEW_ATTENDANT"
)

var CONSUMER_TOPICS = []string{
	CANCEL_CHECK_PAD_ITEM,
	PREPARE_CHECK_PAD_ITEM,
	FORWARD_CHECK_PAD_ITEM,
	DELIVER_CHECK_PAD_ITEM,

	OPEN_CHECK_PAD,
	PAY_CHECK_PAD,

	NEW_CUSTOMER,
	NEW_PLACE,
	NEW_ATTENDANT,
}
