package topic

const (
	NEW_GUEST_CHECK_ITEM     string = "NEW_GUEST_CHECK_ITEM"
	CANCEL_GUEST_CHECK_ITEM  string = "CANCEL_GUEST_CHECK_ITEM"
	PREPARE_GUEST_CHECK_ITEM string = "PREPARE_GUEST_CHECK_ITEM"
	READY_GUEST_CHECK_ITEM   string = "READY_GUEST_CHECK_ITEM"
	FORWARD_GUEST_CHECK_ITEM string = "FORWARD_GUEST_CHECK_ITEM"
	DELIVER_GUEST_CHECK_ITEM string = "DELIVER_GUEST_CHECK_ITEM"

	NEW_GUEST_CHECK          string = "NEW_GUEST_CHECK"
	OPEN_GUEST_CHECK         string = "OPEN_GUEST_CHECK"
	WAIT_PAYMENT_GUEST_CHECK string = "WAIT_PAYMENT_GUEST_CHECK"
	CANCEL_GUEST_CHECK       string = "CANCEL_GUEST_CHECK"
	PAY_GUEST_CHECK          string = "PAY_GUEST_CHECK"

	NEW_GUEST     string = "NEW_GUEST"
	NEW_PLACE     string = "NEW_PLACE"
	NEW_ATTENDANT string = "NEW_ATTENDANT"
)

var CONSUMER_TOPICS = []string{
	CANCEL_GUEST_CHECK_ITEM,
	PREPARE_GUEST_CHECK_ITEM,
	READY_GUEST_CHECK_ITEM,
	FORWARD_GUEST_CHECK_ITEM,
	DELIVER_GUEST_CHECK_ITEM,

	OPEN_GUEST_CHECK,
	PAY_GUEST_CHECK,

	NEW_GUEST,
	NEW_PLACE,
	NEW_ATTENDANT,
}
