package topic

const (
	NEW_GUEST_CHECK  string = "NEW_GUEST_CHECK"
	OPEN_GUEST_CHECK string = "OPEN_GUEST_CHECK"

	NEW_GUEST        string = "NEW_GUEST"
	NEW_PLACE        string = "NEW_PLACE"
	NEW_EMPLOYEE     string = "NEW_EMPLOYEE"
	NEW_MENU_ITEM    string = "NEW_MENU_ITEM"
	UPDATE_MENU_ITEM string = "UPDATE_MENU_ITEM"
)

var CONSUMER_TOPICS = []string{
	OPEN_GUEST_CHECK,

	NEW_GUEST,
	NEW_PLACE,
	NEW_EMPLOYEE,
	NEW_MENU_ITEM,
	UPDATE_MENU_ITEM,
}
