apiVersion: v1
kind: Service
metadata:
  name: guest-check
  labels:
    app: guest-check
    service: guest-check
spec:
  type: ClusterIP
  selector:
    app: guest-check
  ports:
  - name: rest
    port: 8080
    targetPort: 8080
